### ISSUE TITLE
When will the LiDAR data be released?

### ISSUE THREAD

**Issue by Tompson11** [JokerJohn/PRCV-VSLAM-Challenge-2022#1]
Thank you for sharing your great dataset! I've noticed that the LiDAR data are not provided in the SLAM competition. Will the LiDAR data be released some day in the future?

**Comment by JokerJohn** [comment]
> Thank you for sharing your great dataset! I've noticed that the LiDAR data are not provided in the SLAM competition. Will the LiDAR data be released some day in the future?

Hi，Tomopson! We plan to release all these data after October.
