### ISSUE TITLE
How to download a dataset?

### ISSUE THREAD

**Issue by haibo9916** [JokerJohn/PRCV-VSLAM-Challenge-2022#3]
The data download connection provided in this webpage cannot be opened. How can I download it? @gogojjh @JokerJohn @Daisy-GENG @cranesoar

**Comment by JokerJohn** [comment]
> The data download connection provided in this webpage cannot be opened. How can I download it? @gogojjh @JokerJohn @Daisy-GENG @cranesoar

Thans for your feedback! we have fixed this issue, you can download now!

**Comment by haibo9916** [comment]
> > The data download connection provided in this webpage cannot be opened. How can I download it? @gogojjh @JokerJohn @Daisy-GENG @cranesoar
> 
> Thans for your feedback! we have fixed this issue, you can download now!

Sorry, this dataset can't be downloaded yet. I can go to the official Google website, but I can't download this dataset.
![image](https://user-images.githubusercontent.com/65943417/200208817-f75e479a-5957-48e8-a733-974656869328.png)

**Comment by haibo9916** [comment]
@JokerJohn @gogojjh @Daisy-GENG @cranesoar The URL is error
![image](https://user-images.githubusercontent.com/65943417/201257540-02e716f4-4481-460f-9cc7-28860487e71f.png)

**Comment by JokerJohn** [comment]
> @JokerJohn @gogojjh @Daisy-GENG @cranesoar The URL is error ![image](https://user-images.githubusercontent.com/65943417/201257540-02e716f4-4481-460f-9cc7-28860487e71f.png)

[link](http://443r4f2626.goho.co:8001/)

**Comment by JokerJohn** [comment]
![image](https://user-images.githubusercontent.com/25702851/201263890-8c7bc3d9-e622-4f46-9f77-7c0226e7f6a1.png)

**Comment by haibo9916** [comment]
> ![image](https://user-images.githubusercontent.com/25702851/201263890-8c7bc3d9-e622-4f46-9f77-7c0226e7f6a1.png)

thanks
