### ISSUE TITLE
Cannot donwload the dataset

### ISSUE THREAD

**Issue by JiangFengg** [JokerJohn/PRCV-VSLAM-Challenge-2022#4]

**Comment by JiangFengg** [comment]
The data download connection provided in this webpage cannot be opened. How can I download it? @gogojjh @JokerJohn @Daisy-GENG @cranesoar

**Comment by gogojjh** [comment]
Please have a try:
http://filebrowser.ram-lab.com/share/fZtkpO9X

**Comment by JiangFengg** [comment]
> 

thank you very very much for your help
