### ISSUE TITLE
Does this dataset include  depth images?

### ISSUE THREAD

**Issue by akawincent** [JokerJohn/PRCV-VSLAM-Challenge-2022#5]
I need RGB-D sequences and point clounds from Lidar motion.
So I want to ask if this dataset contains RGB-D sequences or just RGB sequences.
Looking forward to your answer！

**Comment by gogojjh** [comment]
RGB without depth sequences are included.

**Comment by akawincent** [comment]
@gogojjh  Thanks for your help！   
Also, I would like to ask one more question. 
Does this dataset include groundtruth point clounds? 
I want to generate groundtruth mesh.

**Comment by JokerJohn** [comment]
yes, we have high-resolution point cloud RGB map collected by Leica BLK 360. you can refer to this [website](https://ram-lab.com/file/site/fusionportable/dataset/fusionportable/#some-high-resolution-gt-maps). 
<img width="1227" alt="image" src="https://github.com/JokerJohn/PRCV-VSLAM-Challenge-2022/assets/25702851/08849009-4444-4c99-9463-afa6226253e0">

**Comment by akawincent** [comment]
@JokerJohn  Good！  Thanks for your help！
