### ISSUE TITLE
about extrinsics from the ouster (reference) to frame_cam00 (target)

### ISSUE THREAD

**Issue by lucky9-cyou** [JokerJohn/PRCV-VSLAM-Challenge-2022#6]
when i use following code to transform ouster pcd to frame cam 00 depth image:
```python
import open3d as o3d
import numpy as np
import os
import cv2

DATA_PATH = 'point/data/'
CAMERA_INTRINSICS = [[6.05128601e+02, 0., 5.20453430e+02],
                    [0., 6.04974060e+02, 3.93878479e+02],
                    [0., 0., 1. ]]
LIDAR_TO_IMG = [-0.4888, 0.5074, -0.4982, 0.5054, 0.0419, 0.0739, -0.0399]
IMAGE_SIZE = (768, 1024)

if not os.path.exists('depth'):
    os.makedirs('depth', exist_ok=True)

from scipy.spatial.transform import Rotation

lidar2img = np.eye(4)
lidar2img[:3, :3] = Rotation.from_quat(LIDAR_TO_IMG[:4]).as_matrix()
lidar2img[:3, 3] = LIDAR_TO_IMG[4:]

print(lidar2img)

# iterate over all the files in the directory
for file in os.listdir(DATA_PATH):
    if file != '000001.pcd':
        continue
    pcd = o3d.io.read_point_cloud(DATA_PATH + file)
    pcd_np = np.concatenate((np.asarray(pcd.points).T, np.ones((1, np.asarray(pcd.points).shape[0]))), axis=0)
    pcd_camera = lidar2img @ pcd_np
    
    positive_pcd = pcd_camera[2, :] > 0
    depth_image = CAMERA_INTRINSICS @ pcd_camera[:3, positive_pcd]
    depth = depth_image[2, :]
    uv = depth_image / depth_image[2, :]
    
    uv_camera_index = np.logical_and(np.logical_and(uv[0, :] < IMAGE_SIZE[1], uv[0, :] >= 0), np.logical_and(uv[1, :] < IMAGE_SIZE[0], uv[1, :] >= 0))
    depth_uv = depth[uv_camera_index]
    depth_image = np.zeros(IMAGE_SIZE)
    depth_image[uv[1, uv_camera_index].astype(int), uv[0, uv_camera_index].astype(int)] = depth_uv
    
    cv2.imwrite('depth.png', (depth_image / depth_image.max() * 255).astype(np.uint8))
    cv2.waitKey(0)
    break
```

I got error depth image, may be the extrinsics is from frame cam00 to ouster in [ouster.yaml](http://filebrowser.ram-lab.com/share/I67uNo6q/20220209_calib/calib/ouster00.yaml)?

The depth image is as follows:
![image](https://github.com/JokerJohn/PRCV-VSLAM-Challenge-2022/assets/56758695/be066f04-ab2c-464b-a60d-b2d8cbb6819a)

**Comment by lucky9-cyou** [comment]
when i use np.linalg.inv(lidar2img), i got an image that seems to be correct
![image](https://github.com/JokerJohn/PRCV-VSLAM-Challenge-2022/assets/56758695/cb7acac4-1cd8-4d10-8ee1-499738c128b0)

**Comment by lucky9-cyou** [comment]
the frame cam 00 image is as follows:
![image](https://github.com/JokerJohn/PRCV-VSLAM-Challenge-2022/assets/56758695/926f2d5a-bd7e-4665-b9e2-7092c0460d4c)

**Comment by gogojjh** [comment]
The possible problem could be the definition of quaternion. Please check our new provided toolbox to parse the yaml files: https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/blob/615c24e247289f7f0d8540ac815fbe565b4f1dc6/data_loader/calib/intrinsic_extrinsic_loader.py#L69

**Comment by lucky9-cyou** [comment]
> The possible problem could be the definition of quaternion. Please check our new provided toolbox to parse the yaml files: https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/blob/615c24e247289f7f0d8540ac815fbe565b4f1dc6/data_loader/calib/intrinsic_extrinsic_loader.py#L69

I have already changed the quaternion order; the code above and the image are the results after the swap.

**Comment by lucky9-cyou** [comment]
I've found my issue. I should check the timestamp to see if the point cloud is projected correctly, rather than looking at the name of the picture. Thanks for your help very much.
